### ISSUE TITLE
no longer working on Blender 3.6 lts - apple silicon

### ISSUE THREAD

**Issue by kvdml** [mrtripie/-Blender-Batch-Export#9]
Errors as soon as I hit the export button.
MacOS Ventura 13.1
Blender 3.6 LTS

Python: Traceback (most recent call last):
  File "/Users/kristofvandommele/Library/Application Support/Blender/3.6/scripts/addons/my_batch_export/__init__.py", line 264, in execute
    self.export_selection(obj.name, context, base_dir)
  File "/Users/kristofvandommele/Library/Application Support/Blender/3.6/scripts/addons/my_batch_export/__init__.py", line 400, in export_selection
    bpy.ops.export_scene.gltf(**options)
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "convert_lighting_mode" unrecognized

**Comment by mrtripie** [comment]
From the error it looks like at least one setting on Blender's gltf exporter has been either removed, or renamed, making your export preset out of date. Blender has some code to keep backwards compatibility with previous version's presets, but this addon doesn't. Updating the preset should fix the error. (Go to File > Export > gltf, choose the preset, and press + to create a new preset, and give it the same name the old version had)
